// SEO metadata configuration for MOTARRO Supplies
import { Metadata } from 'next'

export const metadata: Metadata = {
  title: {
    default: "MOTARRO Supplies | Custom Printed Apparel, Accessories & Promotional Goods",
    template: "%s | MOTARRO Supplies"
  },
  description: "Shop MOTARRO Supplies for high-quality printed apparel, custom printed apparel, and accessories in South Africa. Premium apparel, custom printed clothing, t-shirts, hoodies, and branded merchandise with fast shipping to Johannesburg and Kempton Park.",
  keywords: [
    // CRITICAL: High-impression keywords from Search Console
    "apparel",
    "apparel clothing",
    "printed apparel",
    "printed apparel south africa",
    "custom printed apparel",
    "custom printed apparel south africa",
    "ladies custom apparel",
    "men's custom apparel",
    "mens custom apparel",
    "custom t-shirts South Africa",
    "custom t-shirts south africa",
    "tshirts South Africa",
    "tshirts south africa",
    "t-shirts South Africa",
    "t-shirts south africa",
    "t shirts South Africa",
    "t shirts south africa",
    "custom tshirts",
    "custom t-shirts",
    "custom t shirts",
    "branded clothing",
    "branded clothing south africa",
    "promotional merchandise",
    "promotional merchandise south africa",
    "corporate gifts",
    "corporate gifts south africa",
    "event apparel",
    "event apparel south africa",
    "custom hoodies",
    "custom hoodies south africa",
    "personalized accessories",
    "personalized accessories south africa",
    // Printing methods
    "sublimation printing",
    "sublimation printing johannesburg",
    "sublimation printing south africa",
    "DTG printing",
    "direct to garment printing",
    "screen printing",
    "screen printing johannesburg",
    "screen printing south africa",
    "embroidery services",
    "embroidery services johannesburg",
    "embroidery services south africa",
    "heat transfer printing",
    "bulk custom clothing",
    "bulk custom clothing south africa",
    "branded merchandise",
    "branded merchandise south africa",

    // City variations with lowercase
    "custom apparel Johannesburg",
    "custom apparel johannesburg",
    "custom t-shirts Johannesburg",
    "custom t-shirts johannesburg",
    "tshirts Johannesburg",
    "tshirts johannesburg",
    "t-shirts Johannesburg",
    "t-shirts johannesburg",
    "t shirts Johannesburg",
    "t shirts johannesburg",
    "custom apparel Kempton Park",
    "custom apparel kempton park",
    "custom t-shirts Kempton Park",
    "custom t-shirts kempton park",
    "tshirts Kempton Park",
    "tshirts kempton park",
    "t-shirts Kempton Park",
    "t-shirts kempton park",
    "t shirts Kempton Park",
    "t shirts kempton park",
    "custom apparel Joburg",
    "custom apparel joburg",
    "custom t-shirts Joburg",
    "custom t-shirts joburg",
    "tshirts Joburg",
    "tshirts joburg",
    "t-shirts Joburg",
    "t-shirts joburg",
    "t shirts Joburg",
    "t shirts joburg",

    // Additional combinations with lowercase
    "custom printed t-shirts",
    "custom printed t-shirts south africa",
    "custom printed tshirts",
    "custom printed tshirts south africa",
    "custom printed t shirts",
    "custom printed t shirts south africa",
    "printed t-shirts South Africa",
    "printed t-shirts south africa",
    "printed tshirts South Africa",
    "printed tshirts south africa",
    "printed t shirts South Africa",
    "printed t shirts south africa",
    "custom clothing South Africa",
    "custom clothing south africa",
    "custom apparel South Africa",
    "custom apparel south africa",
    "printed clothing South Africa",
    "printed clothing south africa",
    "printed apparel South Africa",
    "printed apparel south africa",

    // Additional variations
    "custom printed clothing",
    "custom printed clothing south africa",
    "custom printed clothing johannesburg",
    "custom printed clothing kempton park",
    "custom printed clothing joburg",
    "printed clothing johannesburg",
    "printed clothing kempton park",
    "printed clothing joburg",
    "custom apparel johannesburg",
    "custom apparel kempton park",
    "custom apparel joburg",
    "printed apparel johannesburg",
    "printed apparel kempton park",
    "printed apparel joburg",
    "custom t-shirts johannesburg",
    "custom t-shirts kempton park",
    "custom t-shirts joburg",
    "tshirts johannesburg",
    "tshirts kempton park",
    "tshirts joburg",
    "t-shirts johannesburg",
    "t-shirts kempton park",
    "t-shirts joburg",
    "t shirts johannesburg",
    "t shirts kempton park",
    "t shirts joburg",

    // Trending keywords from Google Trends
    "print",
    "clothes",
    "hoodie",
    "jacket",
    "winter",
    "jersey",
    "custom",
    "custom print South Africa",
    "custom clothes South Africa",
    "custom hoodie South Africa",
    "custom jacket South Africa",
    "custom winter apparel South Africa",
    "custom jersey South Africa",
    "print Johannesburg",
    "clothes Johannesburg",
    "hoodie Johannesburg",
    "jacket Johannesburg",
    "winter Johannesburg",
    "jersey Johannesburg",
    "custom Johannesburg",
    "print Kempton Park",
    "clothes Kempton Park",
    "hoodie Kempton Park",
    "jacket Kempton Park",
    "winter Kempton Park",
    "jersey Kempton Park",
    "custom Kempton Park",
    "print Joburg",
    "clothes Joburg",
    "hoodie Joburg",
    "jacket Joburg",
    "winter Joburg",
    "jersey Joburg",
    "custom Joburg",

    // Long-tail keywords
    "custom printed t-shirts Johannesburg South Africa",
    "custom printed hoodies Kempton Park",
    "bulk custom clothing orders South Africa",
    "corporate branded clothing Johannesburg",
    "event t-shirts custom printing South Africa",
    "promotional merchandise printing Johannesburg",
    "screen printing services South Africa",
    "embroidery services Johannesburg",
    "custom workwear South Africa",
    "branded polo shirts Johannesburg",
    
    // Seasonal keywords
    "winter custom clothing South Africa",
    "summer custom t-shirts Johannesburg",
    "school uniform printing South Africa",
    "sports team clothing Johannesburg",
    
    // Industry-specific
    "restaurant staff uniforms Johannesburg",
    "hotel staff clothing South Africa",
    "retail staff uniforms Johannesburg",
    "construction workwear South Africa",
    
    // Product-specific keywords
    "custom hoodies",
    "custom hoodies johannesburg",
    "custom polo shirts",
    "custom caps",
    "custom hats",
    "custom bags",
    "custom mugs",
    "custom phone cases",
    
    // Business/Corporate services
    "corporate uniforms",
    "corporate uniforms johannesburg",
    "business uniforms",
    "work uniforms",
    "promotional clothing",
    "branded workwear",
    "employee uniforms",
    
    // Event/School services
    "school uniforms",
    "school uniform printing",
    "event merchandise",
    "sports team uniforms",
    "graduation apparel",
    "fundraiser t-shirts",
    
    // Local SEO
    "custom clothing near me Johannesburg",
    "t-shirt printing near me Kempton Park",
    "custom apparel Johannesburg East Rand",
    "printed clothing Gauteng",
    "apparel Kempton Park",
    "printed apparel Kempton Park",
    "custom printing Kempton Park",
    "apparel Gauteng",
    "printed apparel Gauteng"
  ],
  openGraph: {
    title: "MOTARRO Supplies | Custom Printed Apparel, Accessories & Promotional Goods",
    description: "Shop MOTARRO Supplies for high-quality printed apparel and custom printed apparel in South Africa. Premium apparel, accessories, and promotional goods. Design your own t-shirts, hoodies, and branded merchandise in Johannesburg.",
    url: "https://www.motarro.co.za",
    siteName: "MOTARRO Supplies",
    images: [
      {
        url: "https://hkervihhlhktjdxcekhi.supabase.co/storage/v1/object/public/product-images/LOGO.PNG",
        width: 1200,
        height: 630,
        alt: "MOTARRO Supplies — Custom Printed Apparel & Accessories"
      }
    ],
    type: "website",
    locale: "en_ZA"
  },
  twitter: {
    card: "summary_large_image",
    title: "MOTARRO Supplies | Custom Printed Apparel, Accessories & Promotional Goods",
    description: "Shop MOTARRO Supplies for high-quality custom printed apparel, accessories, and promotional goods in South Africa.",
    images: ["https://hkervihhlhktjdxcekhi.supabase.co/storage/v1/object/public/product-images/LOGO.PNG"],
    creator: "@motarrosupplies"
  },
  alternates: {
    canonical: "https://www.motarro.co.za"
  },
  robots: {
    index: true,
    follow: true,
    googleBot: {
      index: true,
      follow: true,
      'max-video-preview': -1,
      'max-image-preview': 'large',
      'max-snippet': -1,
    },
  },
  verification: {
    google: 'oOypDfSvdA7fI1EV30uI7a6SebrV3MTZqGxwk5gG_Gc'
  }
}